server:
  port: 8080

spring:
  application:
    name: Mossy
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  elasticsearch:
    uris:
      - localhost:9200
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  batch:
    job:
      enabled: false  # 스케줄러로만 실행하기 위해 애플리케이션 시작 시 Job 자동 실행 방지
    jdbc:
      initialize-schema: embedded  # embedded: 내장 DB만 스키마 자동 생성 / always: 항상 생성 / never: 생성 안함

##swagger
springdoc:
  swagger-ui:
    path: /mossy-docs
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

jwt:
  secret: mossy-secret-key-change-later-32bytes-minimum!!
  access-token-expire-ms: 180000
  refresh-token-expire-ms: 1209600000


encryption:
  secret-key: mossy-encrypt-key-must-be-32byte
  
market:
  policy:
    cart:
      max_quantity: 100


