server:
  port: 8080
spring:
  application:
    name: Mossy
  profiles:
    active: dev # 기본 실행 프로필을 dev로 설정
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  cache:
    type: redis

springdoc:
  swagger-ui:
    path: /mossy-docs
  api-docs:
    path: /v3/api-docs

market:
  policy:
    cart:
      max_quantity: 100